### PR TITLE
Fix: Change autofix to suggestion in `require-meta-schema` rule

### LINKED ISSUE #183: `require-meta-schema`: Change autofix to suggestion
> the autofix will introduce a breaking change for users when passing unknown options:
>
> before autofix: skip validating and lint working fine.
> after autofix: an error thrown from eslint.

Relevant: https://github.com/eslint/eslint#semantic-versioning-policy

_Originally posted by @aladdin-add in https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/182#issuecomment-926292475_

### PR DESCRIPTION
**Pull request by bmish**
Fixes #183.

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]
LGTM~

**Comment by bmish** [comment]
I had to push a fix for ESLint 6 since it appears ESLint 6 doesn't properly handle bailing out of a suggestion function. Good thing we have tests for ESLint 6.

**Comment by bmish** [comment]
I think we're ready for a patch release now. After the patch release, we can do a pre-release of v4.

**Comment by aladdin-add** [comment]
will do.

**Comment by aladdin-add** [comment]
released v3.6.1. 🚀

**Pull request merged**
