### PR TITLE
breaking: drop eslint < 7 & node.js < 10

### LINKED ISSUE #94: Support ESLint 7.x
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

devDependencies should be compatible with ESLint 7 too before we can merge this one:

- [ ] [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node/issues/223)
  - [ ]  [PR](https://github.com/mysticatea/eslint-plugin-node/pull/224)
  - [ ]  Released

---

BREAKING CHANGE: Requires Node@^10.12.x || 12.x
BREAKING CHANGE: Requires ESLint@^7.x

Closes #94

### CODE REVIEW

**Comment by xjamundx** [comment]
Could we remove the dev Dep ?

**Comment by MichaelDeBoey** [comment]
Since all tests are green for ESLint 7.x, I think we can merge this one without https://github.com/mysticatea/eslint-plugin-node/pull/224 being merged 🙂

**Comment by MichaelDeBoey** [comment]
@not-an-aardvark Since all tests are green for ESLint 7.x, I think we can merge this one without https://github.com/mysticatea/eslint-plugin-node/pull/224 being merged 🙂

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!

**Comment by MichaelDeBoey** [comment]
@aladdin-add Any idea when this can be merged and released?

**Comment by xjamundx** [comment]
By this weekend?

**Comment by aladdin-add** [comment]
will have to wait @not-an-aardvark to do a new release, I don't have the access to publish to npm:)

it was written "eslint": ">=5.0.0", so the latest `eslint-plugin-eslint-plugin` has already supported the latest eslint(7.x). is it blocking something else?

**Comment by not-an-aardvark** [comment]
@aladdin-add I just gave you publish access on npm, feel free to publish when you think it's appropriate.

**Comment by aladdin-add** [comment]
released in https://www.npmjs.com/package/eslint-plugin-eslint-plugin/v/3.0.0

**Comment by ljharb** [comment]
Dropping eslint < 7 is very unfortunate, since it means eslint plugins (which often depend on multiple versions of eslint, including the previous major) can't use it without getting npm7 peer deps.

eslint-plugin-react is stuck on v2 of this plugin for effectively ever, unless eslint 6 compat, at least, can be restored.

**Comment by aladdin-add** [comment]
a workaround is to use the `--legacy-peer-deps`.

oc, it seems no harm to restore the eslint v6 compat. will try to release a new version later.👍

**Comment by ljharb** [comment]
Yes, that is indeed what I'm using :-) and thank you, that would be most helpful.

**Comment by aladdin-add** [comment]
released in v3.5.2. 😄

**Pull request merged**
