### PR TITLE
Improve test coverage of `no-identical-tests` rule

### PR DESCRIPTION
**Pull request by bmish**
No behavior change.

### CODE REVIEW

**Comment by bmish** [comment]
@aladdin-add can we get a minor release after this is merged?

**Comment by aladdin-add** [comment]
sure, I will try to do a release tomorrow. :)

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!

**Comment by aladdin-add** [comment]
released in [v3.3.0](https://www.npmjs.com/package/eslint-plugin-eslint-plugin/v/3.3.0).

I have been busy on some rl stuff, sorry for the late! 😄

**Pull request merged**
