### PR TITLE
Update: no-identical-tests despite of properties order.

### LINKED ISSUE #17: rule changes: no-identical-tests.
check indentical tests despite of property order.

```js
{
  code: 'foo',
  options: ['bar']
},
{
  options: ['bar'],
  code: 'foo'
}
```

expected: no errors.
current: report an error.

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
fixes #17

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
@not-an-aardvark all the tests passed, but linting errors. is this the eslint-plugin-self issue?

**Comment by not-an-aardvark** [comment]
It seems like the issue is that the rule is reporting a lot of false positives on the codebase. I don't think this is related to `eslint-plugin-self`.

**Comment by Aladdin-ADD** [comment]
but when add tests that reporting errors, it works well.

**Comment by not-an-aardvark** [comment]
I think the issue is that it's not accounting for test cases which are just shorthand strings.

**Pull request merged**
